[package]
name = "permafrost-common"
description = "Shared model, presets and D-Bus interface for Permafrost"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
zbus.workspace = true
